### ISSUE TITLE
Permission denied for /var/run/docker.sock

### ISSUE THREAD

**Issue by HazCod** [kiyoto/fluent-plugin-docker-metrics#15]
`plugin/in_docker_metrics.rb:103:rescue in on_timer: Permission denied - connect(2) for /var/run/docker.sock (Errno::EACCES)`

My docker run:
```
docker run -d \
    --name fluentd \
    -e DEV_UID=$UID -e DEV_GID=$GID \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$(pwd)/data/logs:/fluentd/log" \
    -p 24224:24224 \
    fluentd

```

**Comment by funkymonkeymonk** [comment]
The default fluentd container runs as user fluent, which doesn't have access to the docker socket. You'll need to change your container to run as root inside the container for this plugin to work.
