### ISSUE TITLE
Value for memory_stat_hierarchical_memory_limit too high

### ISSUE THREAD

**Issue by m3nu** [kiyoto/fluent-plugin-docker-metrics#6]
`memory_stat_hierarchical_memory_limit` causes ES to crash on import because the value is out of range. I simply capped the value for now with `[v.to_i, 9223372036854775807].min`. Maybe drop it altogether?

**Comment by VogonogoV** [comment]
Hi, I'm facing this issue as well. Could you give an example of how to remove the field with the record_reformer or fluent record-transformer?
